import { AcademicCapIcon,
AdjustmentsHorizontalIcon,
AdjustmentsVerticalIcon,
ArchiveBoxArrowDownIcon,
ArchiveBoxXMarkIcon,
ArchiveBoxIcon,
ArrowDownCircleIcon,
ArrowDownLeftIcon,
ArrowDownOnSquareStackIcon,
ArrowDownOnSquareIcon,
ArrowDownRightIcon,
ArrowDownTrayIcon,
ArrowDownIcon,
ArrowLeftCircleIcon,
ArrowLeftEndOnRectangleIcon,
ArrowLeftOnRectangleIcon,
ArrowLeftStartOnRectangleIcon,
ArrowLeftIcon,
ArrowLongDownIcon,
ArrowLongLeftIcon,
ArrowLongRightIcon,
ArrowLongUpIcon,
ArrowPathRoundedSquareIcon,
ArrowPathIcon,
ArrowRightCircleIcon,
ArrowRightEndOnRectangleIcon,
ArrowRightOnRectangleIcon,
ArrowRightStartOnRectangleIcon,
ArrowRightIcon,
ArrowSmallDownIcon,
ArrowSmallLeftIcon,
ArrowSmallRightIcon,
ArrowSmallUpIcon,
ArrowTopRightOnSquareIcon,
ArrowTrendingDownIcon,
ArrowTrendingUpIcon,
ArrowTurnDownLeftIcon,
ArrowTurnDownRightIcon,
ArrowTurnLeftDownIcon,
ArrowTurnLeftUpIcon,
ArrowTurnRightDownIcon,
ArrowTurnRightUpIcon,
ArrowTurnUpLeftIcon,
ArrowTurnUpRightIcon,
ArrowUpCircleIcon,
ArrowUpLeftIcon,
ArrowUpOnSquareStackIcon,
ArrowUpOnSquareIcon,
ArrowUpRightIcon,
ArrowUpTrayIcon,
ArrowUpIcon,
ArrowUturnDownIcon,
ArrowUturnLeftIcon,
ArrowUturnRightIcon,
ArrowUturnUpIcon,
ArrowsPointingInIcon,
ArrowsPointingOutIcon,
ArrowsRightLeftIcon,
ArrowsUpDownIcon,
AtSymbolIcon,
BackspaceIcon,
BackwardIcon,
BanknotesIcon,
Bars2Icon,
Bars3BottomLeftIcon,
Bars3BottomRightIcon,
Bars3CenterLeftIcon,
Bars3Icon,
Bars4Icon,
BarsArrowDownIcon,
BarsArrowUpIcon,
Battery0Icon,
Battery100Icon,
Battery50Icon,
BeakerIcon,
BellAlertIcon,
BellSlashIcon,
BellSnoozeIcon,
BellIcon,
BoldIcon,
BoltSlashIcon,
BoltIcon,
BookOpenIcon,
BookmarkSlashIcon,
BookmarkSquareIcon,
BookmarkIcon,
BriefcaseIcon,
BugAntIcon,
BuildingLibraryIcon,
BuildingOffice2Icon,
BuildingOfficeIcon,
BuildingStorefrontIcon,
CakeIcon,
CalculatorIcon,
CalendarDateRangeIcon,
CalendarDaysIcon,
CalendarIcon,
CameraIcon,
ChartBarSquareIcon,
ChartBarIcon,
ChartPieIcon,
ChatBubbleBottomCenterTextIcon,
ChatBubbleBottomCenterIcon,
ChatBubbleLeftEllipsisIcon,
ChatBubbleLeftRightIcon,
ChatBubbleLeftIcon,
ChatBubbleOvalLeftEllipsisIcon,
ChatBubbleOvalLeftIcon,
CheckBadgeIcon,
CheckCircleIcon,
CheckIcon,
ChevronDoubleDownIcon,
ChevronDoubleLeftIcon,
ChevronDoubleRightIcon,
ChevronDoubleUpIcon,
ChevronDownIcon,
ChevronLeftIcon,
ChevronRightIcon,
ChevronUpDownIcon,
ChevronUpIcon,
CircleStackIcon,
ClipboardDocumentCheckIcon,
ClipboardDocumentListIcon,
ClipboardDocumentIcon,
ClipboardIcon,
ClockIcon,
CloudArrowDownIcon,
CloudArrowUpIcon,
CloudIcon,
CodeBracketSquareIcon,
CodeBracketIcon,
Cog6ToothIcon,
Cog8ToothIcon,
CogIcon,
CommandLineIcon,
ComputerDesktopIcon,
CpuChipIcon,
CreditCardIcon,
CubeTransparentIcon,
CubeIcon,
CurrencyBangladeshiIcon,
CurrencyDollarIcon,
CurrencyEuroIcon,
CurrencyPoundIcon,
CurrencyRupeeIcon,
CurrencyYenIcon,
CursorArrowRaysIcon,
CursorArrowRippleIcon,
DevicePhoneMobileIcon,
DeviceTabletIcon,
DivideIcon,
DocumentArrowDownIcon,
DocumentArrowUpIcon,
DocumentChartBarIcon,
DocumentCheckIcon,
DocumentCurrencyBangladeshiIcon,
DocumentCurrencyDollarIcon,
DocumentCurrencyEuroIcon,
DocumentCurrencyPoundIcon,
DocumentCurrencyRupeeIcon,
DocumentCurrencyYenIcon,
DocumentDuplicateIcon,
DocumentMagnifyingGlassIcon,
DocumentMinusIcon,
DocumentPlusIcon,
DocumentTextIcon,
DocumentIcon,
EllipsisHorizontalCircleIcon,
EllipsisHorizontalIcon,
EllipsisVerticalIcon,
EnvelopeOpenIcon,
EnvelopeIcon,
EqualsIcon,
ExclamationCircleIcon,
ExclamationTriangleIcon,
EyeDropperIcon,
EyeSlashIcon,
EyeIcon,
FaceFrownIcon,
FaceSmileIcon,
FilmIcon,
FingerPrintIcon,
FireIcon,
FlagIcon,
FolderArrowDownIcon,
FolderMinusIcon,
FolderOpenIcon,
FolderPlusIcon,
FolderIcon,
ForwardIcon,
FunnelIcon,
GifIcon,
GiftTopIcon,
GiftIcon,
GlobeAltIcon,
GlobeAmericasIcon,
GlobeAsiaAustraliaIcon,
GlobeEuropeAfricaIcon,
H1Icon,
H2Icon,
H3Icon,
HandRaisedIcon,
HandThumbDownIcon,
HandThumbUpIcon,
HashtagIcon,
HeartIcon,
HomeModernIcon,
HomeIcon,
IdentificationIcon,
InboxArrowDownIcon,
InboxStackIcon,
InboxIcon,
InformationCircleIcon,
ItalicIcon,
KeyIcon,
LanguageIcon,
LifebuoyIcon,
LightBulbIcon,
LinkSlashIcon,
LinkIcon,
ListBulletIcon,
LockClosedIcon,
LockOpenIcon,
MagnifyingGlassCircleIcon,
MagnifyingGlassMinusIcon,
MagnifyingGlassPlusIcon,
MagnifyingGlassIcon,
MapPinIcon,
MapIcon,
MegaphoneIcon,
MicrophoneIcon,
MinusCircleIcon,
MinusSmallIcon,
MinusIcon,
MoonIcon,
MusicalNoteIcon,
NewspaperIcon,
NoSymbolIcon,
NumberedListIcon,
PaintBrushIcon,
PaperAirplaneIcon,
PaperClipIcon,
PauseCircleIcon,
PauseIcon,
PencilSquareIcon,
PencilIcon,
PercentBadgeIcon,
PhoneArrowDownLeftIcon,
PhoneArrowUpRightIcon,
PhoneXMarkIcon,
PhoneIcon,
PhotoIcon,
PlayCircleIcon,
PlayPauseIcon,
PlayIcon,
PlusCircleIcon,
PlusSmallIcon,
PlusIcon,
PowerIcon,
PresentationChartBarIcon,
PresentationChartLineIcon,
PrinterIcon,
PuzzlePieceIcon,
QrCodeIcon,
QuestionMarkCircleIcon,
QueueListIcon,
RadioIcon,
ReceiptPercentIcon,
ReceiptRefundIcon,
RectangleGroupIcon,
RectangleStackIcon,
RocketLaunchIcon,
RssIcon,
ScaleIcon,
ScissorsIcon,
ServerStackIcon,
ServerIcon,
ShareIcon,
ShieldCheckIcon,
ShieldExclamationIcon,
ShoppingBagIcon,
ShoppingCartIcon,
SignalSlashIcon,
SignalIcon,
SlashIcon,
SparklesIcon,
SpeakerWaveIcon,
SpeakerXMarkIcon,
Square2StackIcon,
Square3Stack3DIcon,
Squares2X2Icon,
SquaresPlusIcon,
StarIcon,
StopCircleIcon,
StopIcon,
StrikethroughIcon,
SunIcon,
SwatchIcon,
TableCellsIcon,
TagIcon,
TicketIcon,
TrashIcon,
TrophyIcon,
TruckIcon,
TvIcon,
UnderlineIcon,
UserCircleIcon,
UserGroupIcon,
UserMinusIcon,
UserPlusIcon,
UserIcon,
UsersIcon,
VariableIcon,
VideoCameraSlashIcon,
VideoCameraIcon,
ViewColumnsIcon,
ViewfinderCircleIcon,
WalletIcon,
WifiIcon,
WindowIcon,
WrenchScrewdriverIcon,
WrenchIcon,
XCircleIcon,
XMarkIcon } from '@heroicons/vue/24/outline';


export enum IconName {
	AcademicCapIcon = 'AcademicCapIcon',
	AdjustmentsHorizontalIcon = 'AdjustmentsHorizontalIcon',
	AdjustmentsVerticalIcon = 'AdjustmentsVerticalIcon',
	ArchiveBoxArrowDownIcon = 'ArchiveBoxArrowDownIcon',
	ArchiveBoxXMarkIcon = 'ArchiveBoxXMarkIcon',
	ArchiveBoxIcon = 'ArchiveBoxIcon',
	ArrowDownCircleIcon = 'ArrowDownCircleIcon',
	ArrowDownLeftIcon = 'ArrowDownLeftIcon',
	ArrowDownOnSquareStackIcon = 'ArrowDownOnSquareStackIcon',
	ArrowDownOnSquareIcon = 'ArrowDownOnSquareIcon',
	ArrowDownRightIcon = 'ArrowDownRightIcon',
	ArrowDownTrayIcon = 'ArrowDownTrayIcon',
	ArrowDownIcon = 'ArrowDownIcon',
	ArrowLeftCircleIcon = 'ArrowLeftCircleIcon',
	ArrowLeftEndOnRectangleIcon = 'ArrowLeftEndOnRectangleIcon',
	ArrowLeftOnRectangleIcon = 'ArrowLeftOnRectangleIcon',
	ArrowLeftStartOnRectangleIcon = 'ArrowLeftStartOnRectangleIcon',
	ArrowLeftIcon = 'ArrowLeftIcon',
	ArrowLongDownIcon = 'ArrowLongDownIcon',
	ArrowLongLeftIcon = 'ArrowLongLeftIcon',
	ArrowLongRightIcon = 'ArrowLongRightIcon',
	ArrowLongUpIcon = 'ArrowLongUpIcon',
	ArrowPathRoundedSquareIcon = 'ArrowPathRoundedSquareIcon',
	ArrowPathIcon = 'ArrowPathIcon',
	ArrowRightCircleIcon = 'ArrowRightCircleIcon',
	ArrowRightEndOnRectangleIcon = 'ArrowRightEndOnRectangleIcon',
	ArrowRightOnRectangleIcon = 'ArrowRightOnRectangleIcon',
	ArrowRightStartOnRectangleIcon = 'ArrowRightStartOnRectangleIcon',
	ArrowRightIcon = 'ArrowRightIcon',
	ArrowSmallDownIcon = 'ArrowSmallDownIcon',
	ArrowSmallLeftIcon = 'ArrowSmallLeftIcon',
	ArrowSmallRightIcon = 'ArrowSmallRightIcon',
	ArrowSmallUpIcon = 'ArrowSmallUpIcon',
	ArrowTopRightOnSquareIcon = 'ArrowTopRightOnSquareIcon',
	ArrowTrendingDownIcon = 'ArrowTrendingDownIcon',
	ArrowTrendingUpIcon = 'ArrowTrendingUpIcon',
	ArrowTurnDownLeftIcon = 'ArrowTurnDownLeftIcon',
	ArrowTurnDownRightIcon = 'ArrowTurnDownRightIcon',
	ArrowTurnLeftDownIcon = 'ArrowTurnLeftDownIcon',
	ArrowTurnLeftUpIcon = 'ArrowTurnLeftUpIcon',
	ArrowTurnRightDownIcon = 'ArrowTurnRightDownIcon',
	ArrowTurnRightUpIcon = 'ArrowTurnRightUpIcon',
	ArrowTurnUpLeftIcon = 'ArrowTurnUpLeftIcon',
	ArrowTurnUpRightIcon = 'ArrowTurnUpRightIcon',
	ArrowUpCircleIcon = 'ArrowUpCircleIcon',
	ArrowUpLeftIcon = 'ArrowUpLeftIcon',
	ArrowUpOnSquareStackIcon = 'ArrowUpOnSquareStackIcon',
	ArrowUpOnSquareIcon = 'ArrowUpOnSquareIcon',
	ArrowUpRightIcon = 'ArrowUpRightIcon',
	ArrowUpTrayIcon = 'ArrowUpTrayIcon',
	ArrowUpIcon = 'ArrowUpIcon',
	ArrowUturnDownIcon = 'ArrowUturnDownIcon',
	ArrowUturnLeftIcon = 'ArrowUturnLeftIcon',
	ArrowUturnRightIcon = 'ArrowUturnRightIcon',
	ArrowUturnUpIcon = 'ArrowUturnUpIcon',
	ArrowsPointingInIcon = 'ArrowsPointingInIcon',
	ArrowsPointingOutIcon = 'ArrowsPointingOutIcon',
	ArrowsRightLeftIcon = 'ArrowsRightLeftIcon',
	ArrowsUpDownIcon = 'ArrowsUpDownIcon',
	AtSymbolIcon = 'AtSymbolIcon',
	BackspaceIcon = 'BackspaceIcon',
	BackwardIcon = 'BackwardIcon',
	BanknotesIcon = 'BanknotesIcon',
	Bars2Icon = 'Bars2Icon',
	Bars3BottomLeftIcon = 'Bars3BottomLeftIcon',
	Bars3BottomRightIcon = 'Bars3BottomRightIcon',
	Bars3CenterLeftIcon = 'Bars3CenterLeftIcon',
	Bars3Icon = 'Bars3Icon',
	Bars4Icon = 'Bars4Icon',
	BarsArrowDownIcon = 'BarsArrowDownIcon',
	BarsArrowUpIcon = 'BarsArrowUpIcon',
	Battery0Icon = 'Battery0Icon',
	Battery100Icon = 'Battery100Icon',
	Battery50Icon = 'Battery50Icon',
	BeakerIcon = 'BeakerIcon',
	BellAlertIcon = 'BellAlertIcon',
	BellSlashIcon = 'BellSlashIcon',
	BellSnoozeIcon = 'BellSnoozeIcon',
	BellIcon = 'BellIcon',
	BoldIcon = 'BoldIcon',
	BoltSlashIcon = 'BoltSlashIcon',
	BoltIcon = 'BoltIcon',
	BookOpenIcon = 'BookOpenIcon',
	BookmarkSlashIcon = 'BookmarkSlashIcon',
	BookmarkSquareIcon = 'BookmarkSquareIcon',
	BookmarkIcon = 'BookmarkIcon',
	BriefcaseIcon = 'BriefcaseIcon',
	BugAntIcon = 'BugAntIcon',
	BuildingLibraryIcon = 'BuildingLibraryIcon',
	BuildingOffice2Icon = 'BuildingOffice2Icon',
	BuildingOfficeIcon = 'BuildingOfficeIcon',
	BuildingStorefrontIcon = 'BuildingStorefrontIcon',
	CakeIcon = 'CakeIcon',
	CalculatorIcon = 'CalculatorIcon',
	CalendarDateRangeIcon = 'CalendarDateRangeIcon',
	CalendarDaysIcon = 'CalendarDaysIcon',
	CalendarIcon = 'CalendarIcon',
	CameraIcon = 'CameraIcon',
	ChartBarSquareIcon = 'ChartBarSquareIcon',
	ChartBarIcon = 'ChartBarIcon',
	ChartPieIcon = 'ChartPieIcon',
	ChatBubbleBottomCenterTextIcon = 'ChatBubbleBottomCenterTextIcon',
	ChatBubbleBottomCenterIcon = 'ChatBubbleBottomCenterIcon',
	ChatBubbleLeftEllipsisIcon = 'ChatBubbleLeftEllipsisIcon',
	ChatBubbleLeftRightIcon = 'ChatBubbleLeftRightIcon',
	ChatBubbleLeftIcon = 'ChatBubbleLeftIcon',
	ChatBubbleOvalLeftEllipsisIcon = 'ChatBubbleOvalLeftEllipsisIcon',
	ChatBubbleOvalLeftIcon = 'ChatBubbleOvalLeftIcon',
	CheckBadgeIcon = 'CheckBadgeIcon',
	CheckCircleIcon = 'CheckCircleIcon',
	CheckIcon = 'CheckIcon',
	ChevronDoubleDownIcon = 'ChevronDoubleDownIcon',
	ChevronDoubleLeftIcon = 'ChevronDoubleLeftIcon',
	ChevronDoubleRightIcon = 'ChevronDoubleRightIcon',
	ChevronDoubleUpIcon = 'ChevronDoubleUpIcon',
	ChevronDownIcon = 'ChevronDownIcon',
	ChevronLeftIcon = 'ChevronLeftIcon',
	ChevronRightIcon = 'ChevronRightIcon',
	ChevronUpDownIcon = 'ChevronUpDownIcon',
	ChevronUpIcon = 'ChevronUpIcon',
	CircleStackIcon = 'CircleStackIcon',
	ClipboardDocumentCheckIcon = 'ClipboardDocumentCheckIcon',
	ClipboardDocumentListIcon = 'ClipboardDocumentListIcon',
	ClipboardDocumentIcon = 'ClipboardDocumentIcon',
	ClipboardIcon = 'ClipboardIcon',
	ClockIcon = 'ClockIcon',
	CloudArrowDownIcon = 'CloudArrowDownIcon',
	CloudArrowUpIcon = 'CloudArrowUpIcon',
	CloudIcon = 'CloudIcon',
	CodeBracketSquareIcon = 'CodeBracketSquareIcon',
	CodeBracketIcon = 'CodeBracketIcon',
	Cog6ToothIcon = 'Cog6ToothIcon',
	Cog8ToothIcon = 'Cog8ToothIcon',
	CogIcon = 'CogIcon',
	CommandLineIcon = 'CommandLineIcon',
	ComputerDesktopIcon = 'ComputerDesktopIcon',
	CpuChipIcon = 'CpuChipIcon',
	CreditCardIcon = 'CreditCardIcon',
	CubeTransparentIcon = 'CubeTransparentIcon',
	CubeIcon = 'CubeIcon',
	CurrencyBangladeshiIcon = 'CurrencyBangladeshiIcon',
	CurrencyDollarIcon = 'CurrencyDollarIcon',
	CurrencyEuroIcon = 'CurrencyEuroIcon',
	CurrencyPoundIcon = 'CurrencyPoundIcon',
	CurrencyRupeeIcon = 'CurrencyRupeeIcon',
	CurrencyYenIcon = 'CurrencyYenIcon',
	CursorArrowRaysIcon = 'CursorArrowRaysIcon',
	CursorArrowRippleIcon = 'CursorArrowRippleIcon',
	DevicePhoneMobileIcon = 'DevicePhoneMobileIcon',
	DeviceTabletIcon = 'DeviceTabletIcon',
	DivideIcon = 'DivideIcon',
	DocumentArrowDownIcon = 'DocumentArrowDownIcon',
	DocumentArrowUpIcon = 'DocumentArrowUpIcon',
	DocumentChartBarIcon = 'DocumentChartBarIcon',
	DocumentCheckIcon = 'DocumentCheckIcon',
	DocumentCurrencyBangladeshiIcon = 'DocumentCurrencyBangladeshiIcon',
	DocumentCurrencyDollarIcon = 'DocumentCurrencyDollarIcon',
	DocumentCurrencyEuroIcon = 'DocumentCurrencyEuroIcon',
	DocumentCurrencyPoundIcon = 'DocumentCurrencyPoundIcon',
	DocumentCurrencyRupeeIcon = 'DocumentCurrencyRupeeIcon',
	DocumentCurrencyYenIcon = 'DocumentCurrencyYenIcon',
	DocumentDuplicateIcon = 'DocumentDuplicateIcon',
	DocumentMagnifyingGlassIcon = 'DocumentMagnifyingGlassIcon',
	DocumentMinusIcon = 'DocumentMinusIcon',
	DocumentPlusIcon = 'DocumentPlusIcon',
	DocumentTextIcon = 'DocumentTextIcon',
	DocumentIcon = 'DocumentIcon',
	EllipsisHorizontalCircleIcon = 'EllipsisHorizontalCircleIcon',
	EllipsisHorizontalIcon = 'EllipsisHorizontalIcon',
	EllipsisVerticalIcon = 'EllipsisVerticalIcon',
	EnvelopeOpenIcon = 'EnvelopeOpenIcon',
	EnvelopeIcon = 'EnvelopeIcon',
	EqualsIcon = 'EqualsIcon',
	ExclamationCircleIcon = 'ExclamationCircleIcon',
	ExclamationTriangleIcon = 'ExclamationTriangleIcon',
	EyeDropperIcon = 'EyeDropperIcon',
	EyeSlashIcon = 'EyeSlashIcon',
	EyeIcon = 'EyeIcon',
	FaceFrownIcon = 'FaceFrownIcon',
	FaceSmileIcon = 'FaceSmileIcon',
	FilmIcon = 'FilmIcon',
	FingerPrintIcon = 'FingerPrintIcon',
	FireIcon = 'FireIcon',
	FlagIcon = 'FlagIcon',
	FolderArrowDownIcon = 'FolderArrowDownIcon',
	FolderMinusIcon = 'FolderMinusIcon',
	FolderOpenIcon = 'FolderOpenIcon',
	FolderPlusIcon = 'FolderPlusIcon',
	FolderIcon = 'FolderIcon',
	ForwardIcon = 'ForwardIcon',
	FunnelIcon = 'FunnelIcon',
	GifIcon = 'GifIcon',
	GiftTopIcon = 'GiftTopIcon',
	GiftIcon = 'GiftIcon',
	GlobeAltIcon = 'GlobeAltIcon',
	GlobeAmericasIcon = 'GlobeAmericasIcon',
	GlobeAsiaAustraliaIcon = 'GlobeAsiaAustraliaIcon',
	GlobeEuropeAfricaIcon = 'GlobeEuropeAfricaIcon',
	H1Icon = 'H1Icon',
	H2Icon = 'H2Icon',
	H3Icon = 'H3Icon',
	HandRaisedIcon = 'HandRaisedIcon',
	HandThumbDownIcon = 'HandThumbDownIcon',
	HandThumbUpIcon = 'HandThumbUpIcon',
	HashtagIcon = 'HashtagIcon',
	HeartIcon = 'HeartIcon',
	HomeModernIcon = 'HomeModernIcon',
	HomeIcon = 'HomeIcon',
	IdentificationIcon = 'IdentificationIcon',
	InboxArrowDownIcon = 'InboxArrowDownIcon',
	InboxStackIcon = 'InboxStackIcon',
	InboxIcon = 'InboxIcon',
	InformationCircleIcon = 'InformationCircleIcon',
	ItalicIcon = 'ItalicIcon',
	KeyIcon = 'KeyIcon',
	LanguageIcon = 'LanguageIcon',
	LifebuoyIcon = 'LifebuoyIcon',
	LightBulbIcon = 'LightBulbIcon',
	LinkSlashIcon = 'LinkSlashIcon',
	LinkIcon = 'LinkIcon',
	ListBulletIcon = 'ListBulletIcon',
	LockClosedIcon = 'LockClosedIcon',
	LockOpenIcon = 'LockOpenIcon',
	MagnifyingGlassCircleIcon = 'MagnifyingGlassCircleIcon',
	MagnifyingGlassMinusIcon = 'MagnifyingGlassMinusIcon',
	MagnifyingGlassPlusIcon = 'MagnifyingGlassPlusIcon',
	MagnifyingGlassIcon = 'MagnifyingGlassIcon',
	MapPinIcon = 'MapPinIcon',
	MapIcon = 'MapIcon',
	MegaphoneIcon = 'MegaphoneIcon',
	MicrophoneIcon = 'MicrophoneIcon',
	MinusCircleIcon = 'MinusCircleIcon',
	MinusSmallIcon = 'MinusSmallIcon',
	MinusIcon = 'MinusIcon',
	MoonIcon = 'MoonIcon',
	MusicalNoteIcon = 'MusicalNoteIcon',
	NewspaperIcon = 'NewspaperIcon',
	NoSymbolIcon = 'NoSymbolIcon',
	NumberedListIcon = 'NumberedListIcon',
	PaintBrushIcon = 'PaintBrushIcon',
	PaperAirplaneIcon = 'PaperAirplaneIcon',
	PaperClipIcon = 'PaperClipIcon',
	PauseCircleIcon = 'PauseCircleIcon',
	PauseIcon = 'PauseIcon',
	PencilSquareIcon = 'PencilSquareIcon',
	PencilIcon = 'PencilIcon',
	PercentBadgeIcon = 'PercentBadgeIcon',
	PhoneArrowDownLeftIcon = 'PhoneArrowDownLeftIcon',
	PhoneArrowUpRightIcon = 'PhoneArrowUpRightIcon',
	PhoneXMarkIcon = 'PhoneXMarkIcon',
	PhoneIcon = 'PhoneIcon',
	PhotoIcon = 'PhotoIcon',
	PlayCircleIcon = 'PlayCircleIcon',
	PlayPauseIcon = 'PlayPauseIcon',
	PlayIcon = 'PlayIcon',
	PlusCircleIcon = 'PlusCircleIcon',
	PlusSmallIcon = 'PlusSmallIcon',
	PlusIcon = 'PlusIcon',
	PowerIcon = 'PowerIcon',
	PresentationChartBarIcon = 'PresentationChartBarIcon',
	PresentationChartLineIcon = 'PresentationChartLineIcon',
	PrinterIcon = 'PrinterIcon',
	PuzzlePieceIcon = 'PuzzlePieceIcon',
	QrCodeIcon = 'QrCodeIcon',
	QuestionMarkCircleIcon = 'QuestionMarkCircleIcon',
	QueueListIcon = 'QueueListIcon',
	RadioIcon = 'RadioIcon',
	ReceiptPercentIcon = 'ReceiptPercentIcon',
	ReceiptRefundIcon = 'ReceiptRefundIcon',
	RectangleGroupIcon = 'RectangleGroupIcon',
	RectangleStackIcon = 'RectangleStackIcon',
	RocketLaunchIcon = 'RocketLaunchIcon',
	RssIcon = 'RssIcon',
	ScaleIcon = 'ScaleIcon',
	ScissorsIcon = 'ScissorsIcon',
	ServerStackIcon = 'ServerStackIcon',
	ServerIcon = 'ServerIcon',
	ShareIcon = 'ShareIcon',
	ShieldCheckIcon = 'ShieldCheckIcon',
	ShieldExclamationIcon = 'ShieldExclamationIcon',
	ShoppingBagIcon = 'ShoppingBagIcon',
	ShoppingCartIcon = 'ShoppingCartIcon',
	SignalSlashIcon = 'SignalSlashIcon',
	SignalIcon = 'SignalIcon',
	SlashIcon = 'SlashIcon',
	SparklesIcon = 'SparklesIcon',
	SpeakerWaveIcon = 'SpeakerWaveIcon',
	SpeakerXMarkIcon = 'SpeakerXMarkIcon',
	Square2StackIcon = 'Square2StackIcon',
	Square3Stack3DIcon = 'Square3Stack3DIcon',
	Squares2X2Icon = 'Squares2X2Icon',
	SquaresPlusIcon = 'SquaresPlusIcon',
	StarIcon = 'StarIcon',
	StopCircleIcon = 'StopCircleIcon',
	StopIcon = 'StopIcon',
	StrikethroughIcon = 'StrikethroughIcon',
	SunIcon = 'SunIcon',
	SwatchIcon = 'SwatchIcon',
	TableCellsIcon = 'TableCellsIcon',
	TagIcon = 'TagIcon',
	TicketIcon = 'TicketIcon',
	TrashIcon = 'TrashIcon',
	TrophyIcon = 'TrophyIcon',
	TruckIcon = 'TruckIcon',
	TvIcon = 'TvIcon',
	UnderlineIcon = 'UnderlineIcon',
	UserCircleIcon = 'UserCircleIcon',
	UserGroupIcon = 'UserGroupIcon',
	UserMinusIcon = 'UserMinusIcon',
	UserPlusIcon = 'UserPlusIcon',
	UserIcon = 'UserIcon',
	UsersIcon = 'UsersIcon',
	VariableIcon = 'VariableIcon',
	VideoCameraSlashIcon = 'VideoCameraSlashIcon',
	VideoCameraIcon = 'VideoCameraIcon',
	ViewColumnsIcon = 'ViewColumnsIcon',
	ViewfinderCircleIcon = 'ViewfinderCircleIcon',
	WalletIcon = 'WalletIcon',
	WifiIcon = 'WifiIcon',
	WindowIcon = 'WindowIcon',
	WrenchScrewdriverIcon = 'WrenchScrewdriverIcon',
	WrenchIcon = 'WrenchIcon',
	XCircleIcon = 'XCircleIcon',
	XMarkIcon = 'XMarkIcon',
}

export const IconsMap = {
	[IconName.AcademicCapIcon]: AcademicCapIcon,
	[IconName.AdjustmentsHorizontalIcon]: AdjustmentsHorizontalIcon,
	[IconName.AdjustmentsVerticalIcon]: AdjustmentsVerticalIcon,
	[IconName.ArchiveBoxArrowDownIcon]: ArchiveBoxArrowDownIcon,
	[IconName.ArchiveBoxXMarkIcon]: ArchiveBoxXMarkIcon,
	[IconName.ArchiveBoxIcon]: ArchiveBoxIcon,
	[IconName.ArrowDownCircleIcon]: ArrowDownCircleIcon,
	[IconName.ArrowDownLeftIcon]: ArrowDownLeftIcon,
	[IconName.ArrowDownOnSquareStackIcon]: ArrowDownOnSquareStackIcon,
	[IconName.ArrowDownOnSquareIcon]: ArrowDownOnSquareIcon,
	[IconName.ArrowDownRightIcon]: ArrowDownRightIcon,
	[IconName.ArrowDownTrayIcon]: ArrowDownTrayIcon,
	[IconName.ArrowDownIcon]: ArrowDownIcon,
	[IconName.ArrowLeftCircleIcon]: ArrowLeftCircleIcon,
	[IconName.ArrowLeftEndOnRectangleIcon]: ArrowLeftEndOnRectangleIcon,
	[IconName.ArrowLeftOnRectangleIcon]: ArrowLeftOnRectangleIcon,
	[IconName.ArrowLeftStartOnRectangleIcon]: ArrowLeftStartOnRectangleIcon,
	[IconName.ArrowLeftIcon]: ArrowLeftIcon,
	[IconName.ArrowLongDownIcon]: ArrowLongDownIcon,
	[IconName.ArrowLongLeftIcon]: ArrowLongLeftIcon,
	[IconName.ArrowLongRightIcon]: ArrowLongRightIcon,
	[IconName.ArrowLongUpIcon]: ArrowLongUpIcon,
	[IconName.ArrowPathRoundedSquareIcon]: ArrowPathRoundedSquareIcon,
	[IconName.ArrowPathIcon]: ArrowPathIcon,
	[IconName.ArrowRightCircleIcon]: ArrowRightCircleIcon,
	[IconName.ArrowRightEndOnRectangleIcon]: ArrowRightEndOnRectangleIcon,
	[IconName.ArrowRightOnRectangleIcon]: ArrowRightOnRectangleIcon,
	[IconName.ArrowRightStartOnRectangleIcon]: ArrowRightStartOnRectangleIcon,
	[IconName.ArrowRightIcon]: ArrowRightIcon,
	[IconName.ArrowSmallDownIcon]: ArrowSmallDownIcon,
	[IconName.ArrowSmallLeftIcon]: ArrowSmallLeftIcon,
	[IconName.ArrowSmallRightIcon]: ArrowSmallRightIcon,
	[IconName.ArrowSmallUpIcon]: ArrowSmallUpIcon,
	[IconName.ArrowTopRightOnSquareIcon]: ArrowTopRightOnSquareIcon,
	[IconName.ArrowTrendingDownIcon]: ArrowTrendingDownIcon,
	[IconName.ArrowTrendingUpIcon]: ArrowTrendingUpIcon,
	[IconName.ArrowTurnDownLeftIcon]: ArrowTurnDownLeftIcon,
	[IconName.ArrowTurnDownRightIcon]: ArrowTurnDownRightIcon,
	[IconName.ArrowTurnLeftDownIcon]: ArrowTurnLeftDownIcon,
	[IconName.ArrowTurnLeftUpIcon]: ArrowTurnLeftUpIcon,
	[IconName.ArrowTurnRightDownIcon]: ArrowTurnRightDownIcon,
	[IconName.ArrowTurnRightUpIcon]: ArrowTurnRightUpIcon,
	[IconName.ArrowTurnUpLeftIcon]: ArrowTurnUpLeftIcon,
	[IconName.ArrowTurnUpRightIcon]: ArrowTurnUpRightIcon,
	[IconName.ArrowUpCircleIcon]: ArrowUpCircleIcon,
	[IconName.ArrowUpLeftIcon]: ArrowUpLeftIcon,
	[IconName.ArrowUpOnSquareStackIcon]: ArrowUpOnSquareStackIcon,
	[IconName.ArrowUpOnSquareIcon]: ArrowUpOnSquareIcon,
	[IconName.ArrowUpRightIcon]: ArrowUpRightIcon,
	[IconName.ArrowUpTrayIcon]: ArrowUpTrayIcon,
	[IconName.ArrowUpIcon]: ArrowUpIcon,
	[IconName.ArrowUturnDownIcon]: ArrowUturnDownIcon,
	[IconName.ArrowUturnLeftIcon]: ArrowUturnLeftIcon,
	[IconName.ArrowUturnRightIcon]: ArrowUturnRightIcon,
	[IconName.ArrowUturnUpIcon]: ArrowUturnUpIcon,
	[IconName.ArrowsPointingInIcon]: ArrowsPointingInIcon,
	[IconName.ArrowsPointingOutIcon]: ArrowsPointingOutIcon,
	[IconName.ArrowsRightLeftIcon]: ArrowsRightLeftIcon,
	[IconName.ArrowsUpDownIcon]: ArrowsUpDownIcon,
	[IconName.AtSymbolIcon]: AtSymbolIcon,
	[IconName.BackspaceIcon]: BackspaceIcon,
	[IconName.BackwardIcon]: BackwardIcon,
	[IconName.BanknotesIcon]: BanknotesIcon,
	[IconName.Bars2Icon]: Bars2Icon,
	[IconName.Bars3BottomLeftIcon]: Bars3BottomLeftIcon,
	[IconName.Bars3BottomRightIcon]: Bars3BottomRightIcon,
	[IconName.Bars3CenterLeftIcon]: Bars3CenterLeftIcon,
	[IconName.Bars3Icon]: Bars3Icon,
	[IconName.Bars4Icon]: Bars4Icon,
	[IconName.BarsArrowDownIcon]: BarsArrowDownIcon,
	[IconName.BarsArrowUpIcon]: BarsArrowUpIcon,
	[IconName.Battery0Icon]: Battery0Icon,
	[IconName.Battery100Icon]: Battery100Icon,
	[IconName.Battery50Icon]: Battery50Icon,
	[IconName.BeakerIcon]: BeakerIcon,
	[IconName.BellAlertIcon]: BellAlertIcon,
	[IconName.BellSlashIcon]: BellSlashIcon,
	[IconName.BellSnoozeIcon]: BellSnoozeIcon,
	[IconName.BellIcon]: BellIcon,
	[IconName.BoldIcon]: BoldIcon,
	[IconName.BoltSlashIcon]: BoltSlashIcon,
	[IconName.BoltIcon]: BoltIcon,
	[IconName.BookOpenIcon]: BookOpenIcon,
	[IconName.BookmarkSlashIcon]: BookmarkSlashIcon,
	[IconName.BookmarkSquareIcon]: BookmarkSquareIcon,
	[IconName.BookmarkIcon]: BookmarkIcon,
	[IconName.BriefcaseIcon]: BriefcaseIcon,
	[IconName.BugAntIcon]: BugAntIcon,
	[IconName.BuildingLibraryIcon]: BuildingLibraryIcon,
	[IconName.BuildingOffice2Icon]: BuildingOffice2Icon,
	[IconName.BuildingOfficeIcon]: BuildingOfficeIcon,
	[IconName.BuildingStorefrontIcon]: BuildingStorefrontIcon,
	[IconName.CakeIcon]: CakeIcon,
	[IconName.CalculatorIcon]: CalculatorIcon,
	[IconName.CalendarDateRangeIcon]: CalendarDateRangeIcon,
	[IconName.CalendarDaysIcon]: CalendarDaysIcon,
	[IconName.CalendarIcon]: CalendarIcon,
	[IconName.CameraIcon]: CameraIcon,
	[IconName.ChartBarSquareIcon]: ChartBarSquareIcon,
	[IconName.ChartBarIcon]: ChartBarIcon,
	[IconName.ChartPieIcon]: ChartPieIcon,
	[IconName.ChatBubbleBottomCenterTextIcon]: ChatBubbleBottomCenterTextIcon,
	[IconName.ChatBubbleBottomCenterIcon]: ChatBubbleBottomCenterIcon,
	[IconName.ChatBubbleLeftEllipsisIcon]: ChatBubbleLeftEllipsisIcon,
	[IconName.ChatBubbleLeftRightIcon]: ChatBubbleLeftRightIcon,
	[IconName.ChatBubbleLeftIcon]: ChatBubbleLeftIcon,
	[IconName.ChatBubbleOvalLeftEllipsisIcon]: ChatBubbleOvalLeftEllipsisIcon,
	[IconName.ChatBubbleOvalLeftIcon]: ChatBubbleOvalLeftIcon,
	[IconName.CheckBadgeIcon]: CheckBadgeIcon,
	[IconName.CheckCircleIcon]: CheckCircleIcon,
	[IconName.CheckIcon]: CheckIcon,
	[IconName.ChevronDoubleDownIcon]: ChevronDoubleDownIcon,
	[IconName.ChevronDoubleLeftIcon]: ChevronDoubleLeftIcon,
	[IconName.ChevronDoubleRightIcon]: ChevronDoubleRightIcon,
	[IconName.ChevronDoubleUpIcon]: ChevronDoubleUpIcon,
	[IconName.ChevronDownIcon]: ChevronDownIcon,
	[IconName.ChevronLeftIcon]: ChevronLeftIcon,
	[IconName.ChevronRightIcon]: ChevronRightIcon,
	[IconName.ChevronUpDownIcon]: ChevronUpDownIcon,
	[IconName.ChevronUpIcon]: ChevronUpIcon,
	[IconName.CircleStackIcon]: CircleStackIcon,
	[IconName.ClipboardDocumentCheckIcon]: ClipboardDocumentCheckIcon,
	[IconName.ClipboardDocumentListIcon]: ClipboardDocumentListIcon,
	[IconName.ClipboardDocumentIcon]: ClipboardDocumentIcon,
	[IconName.ClipboardIcon]: ClipboardIcon,
	[IconName.ClockIcon]: ClockIcon,
	[IconName.CloudArrowDownIcon]: CloudArrowDownIcon,
	[IconName.CloudArrowUpIcon]: CloudArrowUpIcon,
	[IconName.CloudIcon]: CloudIcon,
	[IconName.CodeBracketSquareIcon]: CodeBracketSquareIcon,
	[IconName.CodeBracketIcon]: CodeBracketIcon,
	[IconName.Cog6ToothIcon]: Cog6ToothIcon,
	[IconName.Cog8ToothIcon]: Cog8ToothIcon,
	[IconName.CogIcon]: CogIcon,
	[IconName.CommandLineIcon]: CommandLineIcon,
	[IconName.ComputerDesktopIcon]: ComputerDesktopIcon,
	[IconName.CpuChipIcon]: CpuChipIcon,
	[IconName.CreditCardIcon]: CreditCardIcon,
	[IconName.CubeTransparentIcon]: CubeTransparentIcon,
	[IconName.CubeIcon]: CubeIcon,
	[IconName.CurrencyBangladeshiIcon]: CurrencyBangladeshiIcon,
	[IconName.CurrencyDollarIcon]: CurrencyDollarIcon,
	[IconName.CurrencyEuroIcon]: CurrencyEuroIcon,
	[IconName.CurrencyPoundIcon]: CurrencyPoundIcon,
	[IconName.CurrencyRupeeIcon]: CurrencyRupeeIcon,
	[IconName.CurrencyYenIcon]: CurrencyYenIcon,
	[IconName.CursorArrowRaysIcon]: CursorArrowRaysIcon,
	[IconName.CursorArrowRippleIcon]: CursorArrowRippleIcon,
	[IconName.DevicePhoneMobileIcon]: DevicePhoneMobileIcon,
	[IconName.DeviceTabletIcon]: DeviceTabletIcon,
	[IconName.DivideIcon]: DivideIcon,
	[IconName.DocumentArrowDownIcon]: DocumentArrowDownIcon,
	[IconName.DocumentArrowUpIcon]: DocumentArrowUpIcon,
	[IconName.DocumentChartBarIcon]: DocumentChartBarIcon,
	[IconName.DocumentCheckIcon]: DocumentCheckIcon,
	[IconName.DocumentCurrencyBangladeshiIcon]: DocumentCurrencyBangladeshiIcon,
	[IconName.DocumentCurrencyDollarIcon]: DocumentCurrencyDollarIcon,
	[IconName.DocumentCurrencyEuroIcon]: DocumentCurrencyEuroIcon,
	[IconName.DocumentCurrencyPoundIcon]: DocumentCurrencyPoundIcon,
	[IconName.DocumentCurrencyRupeeIcon]: DocumentCurrencyRupeeIcon,
	[IconName.DocumentCurrencyYenIcon]: DocumentCurrencyYenIcon,
	[IconName.DocumentDuplicateIcon]: DocumentDuplicateIcon,
	[IconName.DocumentMagnifyingGlassIcon]: DocumentMagnifyingGlassIcon,
	[IconName.DocumentMinusIcon]: DocumentMinusIcon,
	[IconName.DocumentPlusIcon]: DocumentPlusIcon,
	[IconName.DocumentTextIcon]: DocumentTextIcon,
	[IconName.DocumentIcon]: DocumentIcon,
	[IconName.EllipsisHorizontalCircleIcon]: EllipsisHorizontalCircleIcon,
	[IconName.EllipsisHorizontalIcon]: EllipsisHorizontalIcon,
	[IconName.EllipsisVerticalIcon]: EllipsisVerticalIcon,
	[IconName.EnvelopeOpenIcon]: EnvelopeOpenIcon,
	[IconName.EnvelopeIcon]: EnvelopeIcon,
	[IconName.EqualsIcon]: EqualsIcon,
	[IconName.ExclamationCircleIcon]: ExclamationCircleIcon,
	[IconName.ExclamationTriangleIcon]: ExclamationTriangleIcon,
	[IconName.EyeDropperIcon]: EyeDropperIcon,
	[IconName.EyeSlashIcon]: EyeSlashIcon,
	[IconName.EyeIcon]: EyeIcon,
	[IconName.FaceFrownIcon]: FaceFrownIcon,
	[IconName.FaceSmileIcon]: FaceSmileIcon,
	[IconName.FilmIcon]: FilmIcon,
	[IconName.FingerPrintIcon]: FingerPrintIcon,
	[IconName.FireIcon]: FireIcon,
	[IconName.FlagIcon]: FlagIcon,
	[IconName.FolderArrowDownIcon]: FolderArrowDownIcon,
	[IconName.FolderMinusIcon]: FolderMinusIcon,
	[IconName.FolderOpenIcon]: FolderOpenIcon,
	[IconName.FolderPlusIcon]: FolderPlusIcon,
	[IconName.FolderIcon]: FolderIcon,
	[IconName.ForwardIcon]: ForwardIcon,
	[IconName.FunnelIcon]: FunnelIcon,
	[IconName.GifIcon]: GifIcon,
	[IconName.GiftTopIcon]: GiftTopIcon,
	[IconName.GiftIcon]: GiftIcon,
	[IconName.GlobeAltIcon]: GlobeAltIcon,
	[IconName.GlobeAmericasIcon]: GlobeAmericasIcon,
	[IconName.GlobeAsiaAustraliaIcon]: GlobeAsiaAustraliaIcon,
	[IconName.GlobeEuropeAfricaIcon]: GlobeEuropeAfricaIcon,
	[IconName.H1Icon]: H1Icon,
	[IconName.H2Icon]: H2Icon,
	[IconName.H3Icon]: H3Icon,
	[IconName.HandRaisedIcon]: HandRaisedIcon,
	[IconName.HandThumbDownIcon]: HandThumbDownIcon,
	[IconName.HandThumbUpIcon]: HandThumbUpIcon,
	[IconName.HashtagIcon]: HashtagIcon,
	[IconName.HeartIcon]: HeartIcon,
	[IconName.HomeModernIcon]: HomeModernIcon,
	[IconName.HomeIcon]: HomeIcon,
	[IconName.IdentificationIcon]: IdentificationIcon,
	[IconName.InboxArrowDownIcon]: InboxArrowDownIcon,
	[IconName.InboxStackIcon]: InboxStackIcon,
	[IconName.InboxIcon]: InboxIcon,
	[IconName.InformationCircleIcon]: InformationCircleIcon,
	[IconName.ItalicIcon]: ItalicIcon,
	[IconName.KeyIcon]: KeyIcon,
	[IconName.LanguageIcon]: LanguageIcon,
	[IconName.LifebuoyIcon]: LifebuoyIcon,
	[IconName.LightBulbIcon]: LightBulbIcon,
	[IconName.LinkSlashIcon]: LinkSlashIcon,
	[IconName.LinkIcon]: LinkIcon,
	[IconName.ListBulletIcon]: ListBulletIcon,
	[IconName.LockClosedIcon]: LockClosedIcon,
	[IconName.LockOpenIcon]: LockOpenIcon,
	[IconName.MagnifyingGlassCircleIcon]: MagnifyingGlassCircleIcon,
	[IconName.MagnifyingGlassMinusIcon]: MagnifyingGlassMinusIcon,
	[IconName.MagnifyingGlassPlusIcon]: MagnifyingGlassPlusIcon,
	[IconName.MagnifyingGlassIcon]: MagnifyingGlassIcon,
	[IconName.MapPinIcon]: MapPinIcon,
	[IconName.MapIcon]: MapIcon,
	[IconName.MegaphoneIcon]: MegaphoneIcon,
	[IconName.MicrophoneIcon]: MicrophoneIcon,
	[IconName.MinusCircleIcon]: MinusCircleIcon,
	[IconName.MinusSmallIcon]: MinusSmallIcon,
	[IconName.MinusIcon]: MinusIcon,
	[IconName.MoonIcon]: MoonIcon,
	[IconName.MusicalNoteIcon]: MusicalNoteIcon,
	[IconName.NewspaperIcon]: NewspaperIcon,
	[IconName.NoSymbolIcon]: NoSymbolIcon,
	[IconName.NumberedListIcon]: NumberedListIcon,
	[IconName.PaintBrushIcon]: PaintBrushIcon,
	[IconName.PaperAirplaneIcon]: PaperAirplaneIcon,
	[IconName.PaperClipIcon]: PaperClipIcon,
	[IconName.PauseCircleIcon]: PauseCircleIcon,
	[IconName.PauseIcon]: PauseIcon,
	[IconName.PencilSquareIcon]: PencilSquareIcon,
	[IconName.PencilIcon]: PencilIcon,
	[IconName.PercentBadgeIcon]: PercentBadgeIcon,
	[IconName.PhoneArrowDownLeftIcon]: PhoneArrowDownLeftIcon,
	[IconName.PhoneArrowUpRightIcon]: PhoneArrowUpRightIcon,
	[IconName.PhoneXMarkIcon]: PhoneXMarkIcon,
	[IconName.PhoneIcon]: PhoneIcon,
	[IconName.PhotoIcon]: PhotoIcon,
	[IconName.PlayCircleIcon]: PlayCircleIcon,
	[IconName.PlayPauseIcon]: PlayPauseIcon,
	[IconName.PlayIcon]: PlayIcon,
	[IconName.PlusCircleIcon]: PlusCircleIcon,
	[IconName.PlusSmallIcon]: PlusSmallIcon,
	[IconName.PlusIcon]: PlusIcon,
	[IconName.PowerIcon]: PowerIcon,
	[IconName.PresentationChartBarIcon]: PresentationChartBarIcon,
	[IconName.PresentationChartLineIcon]: PresentationChartLineIcon,
	[IconName.PrinterIcon]: PrinterIcon,
	[IconName.PuzzlePieceIcon]: PuzzlePieceIcon,
	[IconName.QrCodeIcon]: QrCodeIcon,
	[IconName.QuestionMarkCircleIcon]: QuestionMarkCircleIcon,
	[IconName.QueueListIcon]: QueueListIcon,
	[IconName.RadioIcon]: RadioIcon,
	[IconName.ReceiptPercentIcon]: ReceiptPercentIcon,
	[IconName.ReceiptRefundIcon]: ReceiptRefundIcon,
	[IconName.RectangleGroupIcon]: RectangleGroupIcon,
	[IconName.RectangleStackIcon]: RectangleStackIcon,
	[IconName.RocketLaunchIcon]: RocketLaunchIcon,
	[IconName.RssIcon]: RssIcon,
	[IconName.ScaleIcon]: ScaleIcon,
	[IconName.ScissorsIcon]: ScissorsIcon,
	[IconName.ServerStackIcon]: ServerStackIcon,
	[IconName.ServerIcon]: ServerIcon,
	[IconName.ShareIcon]: ShareIcon,
	[IconName.ShieldCheckIcon]: ShieldCheckIcon,
	[IconName.ShieldExclamationIcon]: ShieldExclamationIcon,
	[IconName.ShoppingBagIcon]: ShoppingBagIcon,
	[IconName.ShoppingCartIcon]: ShoppingCartIcon,
	[IconName.SignalSlashIcon]: SignalSlashIcon,
	[IconName.SignalIcon]: SignalIcon,
	[IconName.SlashIcon]: SlashIcon,
	[IconName.SparklesIcon]: SparklesIcon,
	[IconName.SpeakerWaveIcon]: SpeakerWaveIcon,
	[IconName.SpeakerXMarkIcon]: SpeakerXMarkIcon,
	[IconName.Square2StackIcon]: Square2StackIcon,
	[IconName.Square3Stack3DIcon]: Square3Stack3DIcon,
	[IconName.Squares2X2Icon]: Squares2X2Icon,
	[IconName.SquaresPlusIcon]: SquaresPlusIcon,
	[IconName.StarIcon]: StarIcon,
	[IconName.StopCircleIcon]: StopCircleIcon,
	[IconName.StopIcon]: StopIcon,
	[IconName.StrikethroughIcon]: StrikethroughIcon,
	[IconName.SunIcon]: SunIcon,
	[IconName.SwatchIcon]: SwatchIcon,
	[IconName.TableCellsIcon]: TableCellsIcon,
	[IconName.TagIcon]: TagIcon,
	[IconName.TicketIcon]: TicketIcon,
	[IconName.TrashIcon]: TrashIcon,
	[IconName.TrophyIcon]: TrophyIcon,
	[IconName.TruckIcon]: TruckIcon,
	[IconName.TvIcon]: TvIcon,
	[IconName.UnderlineIcon]: UnderlineIcon,
	[IconName.UserCircleIcon]: UserCircleIcon,
	[IconName.UserGroupIcon]: UserGroupIcon,
	[IconName.UserMinusIcon]: UserMinusIcon,
	[IconName.UserPlusIcon]: UserPlusIcon,
	[IconName.UserIcon]: UserIcon,
	[IconName.UsersIcon]: UsersIcon,
	[IconName.VariableIcon]: VariableIcon,
	[IconName.VideoCameraSlashIcon]: VideoCameraSlashIcon,
	[IconName.VideoCameraIcon]: VideoCameraIcon,
	[IconName.ViewColumnsIcon]: ViewColumnsIcon,
	[IconName.ViewfinderCircleIcon]: ViewfinderCircleIcon,
	[IconName.WalletIcon]: WalletIcon,
	[IconName.WifiIcon]: WifiIcon,
	[IconName.WindowIcon]: WindowIcon,
	[IconName.WrenchScrewdriverIcon]: WrenchScrewdriverIcon,
	[IconName.WrenchIcon]: WrenchIcon,
	[IconName.XCircleIcon]: XCircleIcon,
	[IconName.XMarkIcon]: XMarkIcon,
};